const actions = {
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_ERROR: 'REGISTER_ERROR',
    REGISTER_FATALERROR: 'REGISTER_FATALERROR',

    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',
    LOGIN_FATALERROR: 'LOGIN_FATALERROR',

    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_ERROR: 'LOGOUT_ERROR',
    LOGOUT_FATALERROR: 'LOGOUT_FATALERROR',

    CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_ERROR: 'CHANGE_PASSWORD_ERROR',
    CHANGE_PASSWORD_FATALERROR: 'CHANGE_PASSWORD_FATALERROR',

    CHANGE_EMAIL_SUCCESS: 'CHANGE_EMAIL_SUCCESS',
    CHANGE_EMAIL_ERROR: 'CHANGE_EMAIL_ERROR',
    CHANGE_EMAIL_FATALERROR: 'CHANGE_EMAIL_FATALERROR',

    CHANGE_CONTACT_INFO_SUCCESS: 'CHANGE_CONTACT_INFO_SUCCESS',
    CHANGE_CONTACT_INFO_ERROR: 'CHANGE_CONTACT_INFO_ERROR',
    CHANGE_CONTACT_INFO_FATALERROR: 'CHANGE_CONTACT_INFO_FATALERROR',

    FETCH_CUSTOMERS: 'FETCH_CUSTOMERS',
    FETCH_CUSTOMERS_ERROR: 'FETCH_CUSTOMERS_ERROR',
    NEW_CUSTOMER: 'NEW_CUSTOMER'

}
export default actions